cities_with_theaters = [
    "Armenia",
    "Barranquilla",
    "Bogotá",
    "Bucaramanga",
    "Buenaventura",
    "Buga",
    "Cali",
    "Cartagena",
    "Cartago",
    "Caucasia",
    "Chía",
    "Cúcuta",
    "Dosquebradas",
    "Envigado",
    "Florencia",
    "Fusagasugá",
    "Girardot",
    "Guajira",
    "Ibagué",
    "Ipiales",
    "Itagüí",
    "Madrid",
    "Manizales",
    "Medellín",
    "Montería",
    "Mosquera",
    "Neiva",
    "Palmira",
    "Pasto",
    "Pereira",
    "Popayán",
    "Santa Marta",
    "Santo Tomás",
    "Sincelejo",
    "Soledad",
    "Tuluá",
    "Tunja",
    "Valledupar",
    "Villavicencio",
    "Yopal",
    "Yumbo"
]


theaters_by_city = {
    "cine_col": [
        "Armenia", "Barranquilla", "Bogotá", "Bucaramanga", "Cali",
        "Cartagena", "Fusagasugá", "Ibagué", "Manizales", "Medellín",
        "Montería", "Pereira", "Popayán", "Villavicencio"
    ],
    "cinemark": [
        "Armenia", "Bogotá", "Bucaramanga", "Cali", "Cúcuta",
        "Florencia", "Ibagué", "Ipiales", "Medellín", "Montería",
        "Neiva", "Palmira", "Pasto", "Pereira", "Santa Marta",
        "Soledad", "Villavicencio", "Yopal"
    ],
    "cinepolis": [
        "Barranquilla", "Bogotá", "Cali", "Manizales", "Valledupar",
        "Chía", "Envigado"
    ],
    "royal_films": [
        "Armenia", "Barranquilla", "Bogotá", "Bucaramanga", "Buenaventura",
        "Buga", "Cali", "Cartagena", "Cartago", "Caucasia", "Cúcuta",
        "Dosquebradas", "Girardot", "Guajira", "Ibagué", "Itagüí",
        "Madrid", "Medellín", "Montería", "Mosquera", "Neiva", "Pasto",
        "Pereira", "Popayán", "Santo Tomás", "Sincelejo", "Tuluá",
        "Tunja", "Valledupar", "Villavicencio", "Yumbo"
    ],
}


theaters_url = {
    'cinemark' : ['https://www.cinemark.com.co/cartelera/{city}','https://www.cinemark.com.co/cartelera/{city}/{url_name}'],
    'cine_col' : ['https://www.cinecolombia.com','https://www.cinecolombia.com/{city}/peliculas/{url_name}'],
    'cinepolis' : ['https://cinepolis.com.co/cartelera/{city}-colombia/',''], # -> In Theaters link gives the showtimes
    'royal_films' : ['https://cinemasroyalfilms.com/cartelera/{city}', ''], # -> In Theaters link gives the link to the showtimes
}
cities_id_royal = {
    "Armenia": "1015",
    "Barranquilla": "6",
    "Bogotá": "1026",
    "Bucaramanga": "1013",
    "Buenaventura": "1023",
    "Buga": "1021",
    "Cali": "1020",
    "Cartagena": "1043",
    "Cartago": "1034",
    "Cúcuta": "1032",
    "Dosquebradas": "1031",
    "Girardot": "1017",
    "Guajira": "1036",
    "Ibagué": "1027",
    "Ibagué": "1027",
    "Itagüí": "1012",
    "Madellín": "1025",
    "Montería": "1035",
    "Mosquera": "1028",
    "Neiva": "1018",
    "Pasto": "1019",
    "Pereira": "1024",
    "Popayán": "1037",
    "Santo Tomás": "1011",
    "Santa Marta": "1010",
    "Villavicencio": "1042",
    "Yumbo": "1043"
}
cine_colombia_ids = {
    "Armenia": ["6642"],
    "Barranquilla": ["7337", "6772"],
    "Bogotá": [
        "6871",
        "6461",
        "6760",
        "6493",
        "6541",
        "6669",
        "6501",
        "6791",
        "6451",
        "6754",
        "6736",
        "6674",
        "6431",
        "6536",
        "7249",
        "6427",
        "6630",
        "6750",
        "6659",
        "7131",
        "6183"
    ],
    "Bucaramanga": ["6836", "6687", "6444", "6858"],
    "Cali": ["6162", "6742", "6646", "6727", "7011"],
    "Cartagena": ["6401", "6601", "6605"],
    "Fusagasugá": ["7214"],
    "Ibagué": ["6920"],
    "Manizales": ["6485"],
    "Medellín": ["6711", "6690", "6411", "6577", "6365", "6192"],
    "Montería": ["6851"],
    "Pereira": ["6654"],
    "Popayán": ["6172"],
    "Villavicencio": ["6930"]
}
cine_colombia_siteids = {
    "6118": "PORTAL RECARGAS",
    "6162": "CHIPICHAPE",
    "6172": "TERRA PLAZA",
    "6183": "LUMINA",
    "6192": "VIZCAYA",
    "6365": "VIVA ENVIGADO",
    "6401": "CARIBE PLAZA",
    "6411": "SANTAFE MEDELLIN",
    "6427": "PLAZA CENTRAL",
    "6431": "MERCURIO",
    "6444": "DELACUESTA",
    "6451": "CENTRO CHIA",
    "6461": "CENTRO MAYOR",
    "6485": "FUNDADORES",
    "6493": "ANDINO",
    "6501": "CALLE 100",
    "6536": "METROPOLIS",
    "6541": "UNICENTRO",
    "6577": "UNICENTRO MEDELLIN",
    "6601": "PASEO LA CASTELLANA",
    "6605": "PLAZA BOCAGRANDE",
    "6630": "PORTAL 80",
    "6642": "PORTAL DEL QUINDIO",
    "6646": "PALMETTO",
    "6654": "VICTORIA",
    "6659": "SANTAFE BOGOTA",
    "6669": "AVENIDA CHILE",
    "6674": "GRAN ESTACION",
    "6687": "CAÑAVERAL",
    "6690": "MOLINOS",
    "6711": "OVIEDO",
    "6727": "RIO CAUCA",
    "6736": "GALERIAS",
    "6742": "COSMOCENTRO",
    "6750": "PORTOALEGRE",
    "6754": "EMBAJADOR",
    "6760": "AMERICAS",
    "6772": "BUENAVISTA",
    "6791": "CEDRITOS",
    "6836": "CABECERA",
    "6851": "ALAMEDAS DEL SINU",
    "6858": "CACIQUE",
    "6871": "TITAN PLAZA",
    "6920": "LA ESTACION",
    "6930": "VIVA VILLAVICENCIO",
    "7011": "UNICALI",
    "7131": "VENTURA TERREROS",
    "7214": "AVENIDA FUSAGASUGA",
    "7249": "NUESTRO BOGOTA",
    "7337": "PARQUE ALEGRA"
}
