theaters_by_city = {
    "Armenia": {"cinemark", "cine_col", "royal_films"},
    "Barranquilla": {"cine_col", "royal_films", "cinepolis"},
    "Bogotá": {"cinemark", "cine_col", "royal_films", "cinepolis"},
    "Bucaramanga": {"cinemark", "cine_col", "royal_films"},
    "Buenaventura": {"royal_films"},
    "Buga": {"royal_films"},
    "Cali": {"cinemark", "cine_col", "royal_films", "cinepolis"},
    "Cartagena": {"cine_col", "royal_films"},
    "Cartago": {"royal_films"},
    "Caucasia": {"royal_films"},
    "Cúcuta": {"cinemark", "royal_films"},
    "Dosquebradas": {"royal_films"},
    "Florencia": {"cinemark"},
    "Fusagasugá": {"cine_col"},
    "Girardot": {"royal_films"},
    "Guajira": {"royal_films"},
    "Ibagué": {"cinemark", "cine_col", "royal_films"},
    "Ipiales": {"cinemark"},
    "Itagüí": {"royal_films"},
    "Madrid": {"royal_films"},
    "Manizales": {"cine_col", "cinepolis"},
    "Medellín": {"cinemark", "cine_col", "royal_films"},
    "Montería": {"cinemark", "cine_col", "royal_films"},
    "Mosquera": {"royal_films"},
    "Neiva": {"cinemark", "royal_films"},
    "Palmira": {"cinemark"},
    "Pasto": {"cinemark", "royal_films"},
    "Pereira": {"cinemark", "cine_col", "royal_films"},
    "Popayán": {"cine_col", "royal_films"},
    "Santa Marta": {"cinemark"},
    "Santo Tomás": {"royal_films"},
    "Sincelejo": {"royal_films"},
    "Soledad": {"cinemark"},
    "Tuluá": {"royal_films"},
    "Tunja": {"royal_films"},
    "Valledupar": {"royal_films", "cinepolis"},
    "Villavicencio": {"cinemark", "cine_col", "royal_films"},
    "Yopal": {"cinemark"},
    "Yumbo": {"royal_films"},
    "Chía": {"cinepolis"},
    "Envigado": {"cinepolis"},
}

theaters_url = {
    'cinemark' : ['https://www.cinemark.com.co/cartelera/{city}','https://www.cinemark.com.co/cartelera/{city}/{url_name}'],
    'cine_col' : ['https://www.cinecolombia.com/{city}/cartelera','https://www.cinecolombia.com/{city}/peliculas/{url_name}'],
    'cinepolis' : ['https://cinepolis.com.co/cartelera/{city}-colombia/',''], # -> In Theaters link gives the showtimes
    'royal_films' : ['https://cinemasroyalfilms.com/cartelera/{city}', ''], # -> In Theaters link gives the link to the showtimes
}
cities_id_royal = {
    "Armenia": "1015",
    "Barranquilla": "6",
    "Bogotá": "1026",
    "Bucaramanga": "1013",
    "Buenaventura": "1023",
    "Buga": "1021",
    "Cali": "1020",
    "Cartagena": "1043",
    "Cartago": "1034",
    "Cúcuta": "1032",
    "Dosquebradas": "1031",
    "Girardot": "1017",
    "Guajira": "1036",
    "Ibagué": "1027",
    "Ibagué": "1027",
    "Itagüí": "1012",
    "Madellín": "1025",
    "Montería": "1035",
    "Mosquera": "1028",
    "Neiva": "1018",
    "Pasto": "1019",
    "Pereira": "1024",
    "Popayán": "1037",
    "Santo Tomás": "1011",
    "Santa Marta": "1010",
    "Villavicencio": "1042",
    "Yumbo": "1043"
}